### ISSUE TITLE
Volunteer page: Volunteer testimonials

### ISSUE THREAD

**Issue by alex-maletskyi** [HYF-Class21/agile-development-group4-hyf-redesign#22]
- This user story is developed on branch `volunteers-testimonial`
- This branch is merged to `main` branch after completion.
  > As a user i want to know what is like to volunteer for HackYourFuture.

##### Part 1

- Comment this section
- [x] add `section` tag with class `volunteers-testimonial-container`
- [x] add `div` inside `section` with class `volunteers-testimonial-1`
- [x] add `div` inside `volunteers-testimonial-1` div with class `testimonial-img-1`
- [x] add `div` inside `volunteers-testimonial-1` div with class `testimonial-1`
- [x] add `h4` tag with class `volunteer-testimonial-name`
- [x] add `p` tag with class `volunteer-testimonial-position`
- [x] add `p` tag with class `volunteer-testimonial-text`
- [x] inside `testimonial-1` add `a` tag with class `volunteer-discover`

##### Part 2

- Comment this section
- [x] add `section` tag with class `volunteers-testimonial-container`
- [x] add `div` inside `section` with class `volunteers-testimonial-2`
- [x] add `div` inside `volunteers-testimonial-2` div with class `testimonial-img-2`
- [x] add `div` inside `volunteers-testimonial-2` div with class `testimonial-2`
- [x] add `h4` tag with class `volunteer-testimonial-name`
- [x] add `p` tag with class `volunteer-testimonial-position`
- [x] add `p` tag with class `volunteer-testimonial-text`
- [x] inside `testimonial-2` add `a` tag with class `volunteer-discover`
